export const AI_PROFILES_2 = [
    {
        id: 'duelist',
        label: 'Duelist',
        color: 0xff5533,
        preferredRange: 55,
        idealRangeBand: 20,
        aggression: 1.1,
        aimThreshold: 0.84,
        dodge: 0.35,
        wallFear: 1.25,
        pickupBias: 0.55,
        reverseTime: 0.85,
        fireCooldownScale: 0.9
    },
    {
        id: 'brawler',
        label: 'Brawler',
        color: 0xffcc22,
        preferredRange: 28,
        idealRangeBand: 14,
        aggression: 1.3,
        aimThreshold: 0.72,
        dodge: 0.2,
        wallFear: 1.15,
        pickupBias: 0.35,
        reverseTime: 0.75,
        fireCooldownScale: 0.82
    },
    {
        id: 'sniper',
        label: 'Sniper',
        color: 0x66ccff,
        preferredRange: 110,
        idealRangeBand: 28,
        aggression: 0.82,
        aimThreshold: 0.93,
        dodge: 0.18,
        wallFear: 1.35,
        pickupBias: 0.7,
        reverseTime: 0.95,
        fireCooldownScale: 1.12
    },
    {
        id: 'raider',
        label: 'Raider',
        color: 0x33ff88,
        preferredRange: 70,
        idealRangeBand: 18,
        aggression: 1.0,
        aimThreshold: 0.8,
        dodge: 0.5,
        wallFear: 1.1,
        pickupBias: 0.95,
        reverseTime: 0.8,
        fireCooldownScale: 0.95
    },
    {
        id: 'bulldog',
        label: 'Bulldog',
        color: 0xaa66ff,
        preferredRange: 40,
        idealRangeBand: 16,
        aggression: 1.18,
        aimThreshold: 0.78,
        dodge: 0.15,
        wallFear: 1.05,
        pickupBias: 0.25,
        reverseTime: 0.7,
        fireCooldownScale: 0.88
    },
    {
        id: 'trickster',
        label: 'Trickster',
        color: 0xff66cc,
        preferredRange: 75,
        idealRangeBand: 22,
        aggression: 0.96,
        aimThreshold: 0.81,
        dodge: 0.72,
        wallFear: 1.28,
        pickupBias: 0.6,
        reverseTime: 0.9,
        fireCooldownScale: 1.0
    },
    {
        id: 'sentinel',
        label: 'Sentinel',
        color: 0xffffff,
        preferredRange: 88,
        idealRangeBand: 24,
        aggression: 0.9,
        aimThreshold: 0.9,
        dodge: 0.12,
        wallFear: 1.45,
        pickupBias: 0.75,
        reverseTime: 1.0,
        fireCooldownScale: 1.04
    },
    {
        id: 'scavenger',
        label: 'Scavenger',
        color: 0x00ffaa,
        preferredRange: 62,
        idealRangeBand: 20,
        aggression: 0.88,
        aimThreshold: 0.79,
        dodge: 0.42,
        wallFear: 1.2,
        pickupBias: 1.2,
        reverseTime: 0.88,
        fireCooldownScale: 0.97
    }
];
