export const CONFIG = {
    gravity: -9.82, 
    chassisMass: 1500, 
    engineForce: 8000, 
    brakeForce: 60,
    maxSteerVal: 0.5, 
    wheelRadius: 0.6,
    chassisDimensions: { x: 2.5, y: 0.7, z: 4.8 },
    bulletSpeed: 450, 
    mineSpeed: 10, 
    mineCooldown: 5000,
    gears: [ 
        { maxSpeed: 60, torque: 1.2 }, 
        { maxSpeed: 95, torque: 1.0 }, 
        { maxSpeed: 135, torque: 0.8 }, 
        { maxSpeed: 180, torque: 0.6 }, 
        { maxSpeed: 220, torque: 0.45 }, 
        { maxSpeed: 280, torque: 0.35 } 
    ],
    CARS: {
        'beachbug': { 
            name: 'Beach Bug', 
            gltfPath: 'objects/cars/1-beachbug/',
            gltfFile: 'buggy.glb',
            scale: 1.4,
            rotationOffset: Math.PI, 
            offset: { x: 0, y: -0.5, z: 0 },
            team: 1, 
            class: 'Light',
            color: 0xddbb66, 
            dimensions: { x: 2.5, y: 0.7, z: 5.5 }, 
            mass: 1800, 
            stats: { hp: 100, accel: 1.0, topSpeed: 1.0, jumpPower: 1.0, boostMult: 2.0, boostDur: 1.0, energyRegen: 1.0, nitroRegen: 1.0, ultCharge: 0, ultDmg: 1.0, bulletDmg: 1.0, bulletSpeed: 1.0, grip: 1.0 },
            wheels: [ { x: -1.9, y: -0.6, z: 2.8 }, { x: 1.9, y: -0.6, z: 2.8 }, { x: -1.9, y: -0.6, z: -2.8 }, { x: 1.9, y: -0.6, z: -2.8 } ],
            ult: 'Quicksand - Dumps a large quicksand pool that slows enemies for 10s' 
        },
        'foodtruck': { 
            name: 'Food Truck', 
            objPath: 'objects/cars/2-slamfoodtruck/',
            objFile: 'slammedvan.obj',
            mtlFile: 'slammedvan.mtl',
            scale: 1.5,
            rotationOffset: Math.PI, 
            offset: { x: 0, y: -0.6, z: 0 },
            team: 1, 
            class: 'Medium',
            color: 0xcc8844, 
            dimensions: { x: 2.5, y: 0.7, z: 5.5 }, 
            mass: 1800, 
            stats: { hp: 100, accel: 1.0, topSpeed: 1.0, jumpPower: 1.0, boostMult: 2.0, boostDur: 1.0, energyRegen: 1.0, nitroRegen: 1.0, ultCharge: 0, ultDmg: 1.0, bulletDmg: 1.0, bulletSpeed: 1.0, grip: 1.0 },
            wheels: [ { x: -1.9, y: -0.6, z: 2.8 }, { x: 1.9, y: -0.6, z: 2.8 }, { x: -1.9, y: -0.6, z: -2.8 }, { x: 1.9, y: -0.6, z: -2.8 } ],
            ult: 'Smoke Trail - Leaves smoke clouds that prevent enemies from accelerating for 6s' 
        },
        'beachpartyvan': { 
            name: 'Beach Party Van', 
            gltfPath: 'objects/cars/3-partybus/',
            gltfFile: 'paz_652.glb',
            scale: 2.0,
            rotationOffset: Math.PI, 
            offset: { x: 0, y: -0.5, z: 0 },
            team: 1, 
            class: 'Heavy',
            color: 0xff8844, 
            dimensions: { x: 2.5, y: 0.7, z: 5.5 }, 
            mass: 1800, 
            stats: { hp: 100, accel: 1.0, topSpeed: 1.0, jumpPower: 1.0, boostMult: 2.0, boostDur: 1.0, energyRegen: 1.0, nitroRegen: 1.0, ultCharge: 0, ultDmg: 1.0, bulletDmg: 1.0, bulletSpeed: 1.0, grip: 1.0 },
            wheels: [ { x: -1.9, y: -0.6, z: 2.8 }, { x: 1.9, y: -0.6, z: 2.8 }, { x: -1.9, y: -0.6, z: -2.8 }, { x: 1.9, y: -0.6, z: -2.8 } ],
            ult: 'Beach Party Pulse - 4 shockwave pulses that knock enemies up and away' 
        },
        'hovercar': {
            name: 'Hover Car',
            objPath: 'objects/cars/4-hovercar/',
            objFile: 'hovercar.obj',
            mtlFile: 'hovercar.mtl',
            scale: 1.5,
            rotationOffset: Math.PI,
            team: 2,
            class: 'Light',
            color: 0x00ddff,
            dimensions: { x: 2.5, y: 0.7, z: 5.5 },
            mass: 1400,
            stats: { hp: 100, accel: 1.0, topSpeed: 1.0, jumpPower: 1.0, boostMult: 2.0, boostDur: 1.0, energyRegen: 1.0, nitroRegen: 1.0, ultCharge: 0, ultDmg: 1.0, bulletDmg: 1.0, bulletSpeed: 1.0, grip: 1.0 },
            wheels: [],
            ult: 'Default Projectile'
        },
        'rover': {
            name: 'Rover',
            gltfPath: 'objects/cars/5-rover/',
            gltfFile: 'rover.glb',
            scale: 1.0,
            rotationOffset: Math.PI,
            offset: { x: 0, y: -0.5, z: 0 },
            team: 2,
            class: 'Medium',
            color: 0xcc8844,
            dimensions: { x: 2.5, y: 0.7, z: 5.5 },
            mass: 1800,
            stats: { hp: 100, accel: 1.0, topSpeed: 1.0, jumpPower: 1.0, boostMult: 2.0, boostDur: 1.0, energyRegen: 1.0, nitroRegen: 1.0, ultCharge: 0, ultDmg: 1.0, bulletDmg: 1.0, bulletSpeed: 1.0, grip: 1.0 },
            wheels: [ { x: -1.9, y: -0.6, z: 2.8 }, { x: 1.9, y: -0.6, z: 2.8 }, { x: -1.9, y: -0.6, z: -2.8 }, { x: 1.9, y: -0.6, z: -2.8 } ],
            ult: 'Default Projectile'
        },
        'rv': { 
            name: 'RV', 
            objPath: 'objects/cars/6-rv/',
            objFile: 'rv.glb',
            scale: 2.2,
            rotationOffset: Math.PI, 
            offset: { x: 0, y: -0.5, z: 0 },
            team: 2, 
            class: 'Heavy',
            color: 0x88ccff, 
            dimensions: { x: 2.5, y: 0.7, z: 5.5 }, 
            mass: 1800, 
            stats: { hp: 100, accel: 1.0, topSpeed: 1.0, jumpPower: 1.0, boostMult: 2.0, boostDur: 1.0, energyRegen: 1.0, nitroRegen: 1.0, ultCharge: 0, ultDmg: 1.0, bulletDmg: 1.0, bulletSpeed: 1.0, grip: 1.0 },
            wheels: [ { x: -1.9, y: -0.6, z: 2.8 }, { x: 1.9, y: -0.6, z: 2.8 }, { x: -1.9, y: -0.6, z: -2.8 }, { x: 1.9, y: -0.6, z: -2.8 } ],
            ult: 'SAT Drop - Satellite falls from space, shocks nearby enemies on ground' 
        },
        'sidecarbike': { 
            name: 'Sidecar Bike', 
            gltfPath: 'objects/cars/7-sidebike/',
            gltfFile: 'sidecarbike.glb',
            scale: 0.8,
            rotationOffset: Math.PI, 
            offset: { x: 0, y: -0.5, z: 0 },
            team: 3, 
            class: 'Light',
            color: 0x888888, 
            dimensions: { x: 2.5, y: 0.7, z: 5.5 }, 
            mass: 1400, 
            stats: { hp: 100, accel: 1.0, topSpeed: 1.0, jumpPower: 1.0, boostMult: 2.0, boostDur: 1.0, energyRegen: 1.0, nitroRegen: 1.0, ultCharge: 0, ultDmg: 1.0, bulletDmg: 1.0, bulletSpeed: 1.0, grip: 1.0 },
            wheels: [ { x: -1.9, y: -0.6, z: 2.8 }, { x: 1.9, y: -0.6, z: 2.8 }, { x: -1.9, y: -0.6, z: -2.8 }, { x: 1.9, y: -0.6, z: -2.8 } ],
            ult: 'Boomerang Saw - Upright spinning disc flies out and returns like a boomerang' 
        },
        'ratrod': { 
            name: 'Rat Rod AA', 
            gltfPath: 'objects/cars/8-rataa/',
            gltfFile: 'ratrodaa.glb',
            scale: 1.5,
            rotationOffset: Math.PI, 
            offset: { x: 0, y: -0.5, z: 0 },
            team: 3, 
            class: 'Medium',
            color: 0x884422, 
            dimensions: { x: 2.5, y: 0.7, z: 5.5 }, 
            mass: 1800, 
            stats: { hp: 100, accel: 1.0, topSpeed: 1.0, jumpPower: 1.0, boostMult: 2.0, boostDur: 1.0, energyRegen: 1.0, nitroRegen: 1.0, ultCharge: 0, ultDmg: 1.0, bulletDmg: 1.0, bulletSpeed: 1.0, grip: 1.0 },
            wheels: [ { x: -1.9, y: -0.6, z: 2.8 }, { x: 1.9, y: -0.6, z: 2.8 }, { x: -1.9, y: -0.6, z: -2.8 }, { x: 1.9, y: -0.6, z: -2.8 } ],
            ult: 'AA Gun - Hitscan anti-air fire that targets airborne enemies' 
        },
        'amrtruck': {
            name: 'Army Truck',
            objPath: 'objects/cars/9-armytruck/',
            objFile: 'amrtruck.obj',
            mtlFile: 'amrtruck.mtl',
            scale: 2.2,
            rotationOffset: Math.PI,
            offset: { x: 0, y: -0.5, z: 0 },
            team: 3,
            class: 'Heavy',
            color: 0x445522,
            dimensions: { x: 2.5, y: 0.7, z: 5.5 },
            mass: 1800,
            stats: { hp: 100, accel: 1.0, topSpeed: 1.0, jumpPower: 1.0, boostMult: 2.0, boostDur: 1.0, energyRegen: 1.0, nitroRegen: 1.0, ultCharge: 0, ultDmg: 1.0, bulletDmg: 1.0, bulletSpeed: 1.0, grip: 1.0 },
            wheels: [ { x: -1.9, y: -0.6, z: 2.8 }, { x: 1.9, y: -0.6, z: 2.8 }, { x: -1.9, y: -0.6, z: -2.8 }, { x: 1.9, y: -0.6, z: -2.8 } ],
            ult: 'Firebombing - Drops 5 fire pools in a wall of fire behind the truck'
        },
        'sprintracer': {
            name: 'Sprint Racer',
            objPath: 'objects/cars/10-sprint/',
            objFile: 'LOWPOLY_CARIBE_MK1.obj',
            scale: 1.2,
            rotationOffset: Math.PI,
            offset: { x: 0, y: -0.5, z: 0 },
            team: 4,
            class: 'Light',
            color: 0xff4400,
            dimensions: { x: 2.5, y: 0.7, z: 5.5 },
            mass: 1400,
            stats: { hp: 100, accel: 1.0, topSpeed: 1.0, jumpPower: 1.0, boostMult: 2.0, boostDur: 1.0, energyRegen: 1.0, nitroRegen: 1.0, ultCharge: 0, ultDmg: 1.0, bulletDmg: 1.0, bulletSpeed: 1.0, grip: 1.0 },
            wheels: [ { x: -1.9, y: -0.6, z: 2.8 }, { x: 1.9, y: -0.6, z: 2.8 }, { x: -1.9, y: -0.6, z: -2.8 }, { x: 1.9, y: -0.6, z: -2.8 } ],
            ult: 'Volcano Burst - Rapid fire burst that leaves target on fire'
        },
        'bladecybercar': { 
            name: 'Blade Cyber', 
            objPath: 'objects/cars/11-cybercar/',
            objFile: 'hackercar.obj',
            mtlFile: 'hackercar.mtl',
            scale: 1.7,
            rotationOffset: Math.PI, 
            offset: { x: 0, y: -0.2, z: 0 },
            team: 4, 
            class: 'Medium',
            color: 0x00ffff, 
            dimensions: { x: 2.5, y: 0.7, z: 5.5 }, 
            mass: 1500, 
            stats: { hp: 100, accel: 1.0, topSpeed: 1.0, jumpPower: 1.0, boostMult: 2.0, boostDur: 1.0, energyRegen: 1.0, nitroRegen: 1.0, ultCharge: 0, ultDmg: 1.0, bulletDmg: 1.0, bulletSpeed: 1.0, grip: 1.0 },
            wheels: [ { x: -1.9, y: -0.6, z: 2.8 }, { x: 1.9, y: -0.6, z: 2.8 }, { x: -1.9, y: -0.6, z: -2.8 }, { x: 1.9, y: -0.6, z: -2.8 } ],
            ult: 'Default Projectile' 
        },
        '12-servervan': { 
            name: 'Server Van', 
            gltfPath: 'objects/cars/12-servervan/',
            gltfFile: 'servervan.glb',
            scale: 1.9,
            rotationOffset: Math.PI / 2,
            offset: { x: 0, y: -0.4, z: 0 },
            team: 4, 
            class: 'Heavy',
            color: 0x222222, 
            dimensions: { x: 2.6, y: 2.2, z: 6.0 }, 
            mass: 1800, 
            stats: { hp: 100, accel: 1.0, topSpeed: 1.0, jumpPower: 1.0, boostMult: 2.0, boostDur: 1.0, energyRegen: 1.0, nitroRegen: 1.0, ultCharge: 0, ultDmg: 1.0, bulletDmg: 1.0, bulletSpeed: 1.0, grip: 1.0 },
            wheels: [ { x: -1.9, y: -0.6, z: 2.8 }, { x: 1.9, y: -0.6, z: 2.8 }, { x: -1.9, y: -0.6, z: -2.8 }, { x: 1.9, y: -0.6, z: -2.8 } ],
            ult: 'Cryo Nova - Freezes all barrels within 25m' 
        },
        'aicop': {
            name: 'AI Cop',
            objPath: 'objects/cars/13-washme/',
            objFile: 'washme.obj',
            mtlFile: 'washme.mtl',
            scale: 1.0,
            rotationOffset: Math.PI + Math.PI / 2,
            offset: { x: 0, y: -0.5, z: 0 },
            team: 5,
            class: 'Light',
            color: 0x2222cc,
            dimensions: { x: 2.5, y: 0.7, z: 5.5 },
            mass: 1200,
            stats: { hp: 100, accel: 1.0, topSpeed: 1.0, jumpPower: 1.0, boostMult: 2.0, boostDur: 1.0, energyRegen: 1.0, nitroRegen: 1.0, ultCharge: 0, ultDmg: 1.0, bulletDmg: 1.0, bulletSpeed: 1.0, grip: 1.0 },
            wheels: [ { x: -1.9, y: -0.6, z: 2.8 }, { x: 1.9, y: -0.6, z: 2.8 }, { x: -1.9, y: -0.6, z: -2.8 }, { x: 1.9, y: -0.6, z: -2.8 } ],
            ult: 'Default Projectile'
        },
        'policecar': { 
            name: 'Police Car', 
            gltfPath: 'objects/cars/14-cruiser/',
            gltfFile: 'policecar.glb',
            scale: 2.2,
            rotationOffset: Math.PI, 
            offset: { x: 0, y: 0, z: 0 },
            team: 5, 
            class: 'Medium',
            color: 0xffffff, 
            dimensions: { x: 2.5, y: 0.7, z: 5.5 }, 
            mass: 1600, 
            stats: { hp: 100, accel: 1.0, topSpeed: 1.0, jumpPower: 1.0, boostMult: 2.0, boostDur: 1.0, energyRegen: 1.0, nitroRegen: 1.0, ultCharge: 0, ultDmg: 1.0, bulletDmg: 1.0, bulletSpeed: 1.0, grip: 1.0 },
            wheels: [ { x: -1.9, y: -0.6, z: 2.8 }, { x: 1.9, y: -0.6, z: 2.8 }, { x: -1.9, y: -0.6, z: -2.8 }, { x: 1.9, y: -0.6, z: -2.8 } ],
            ult: 'Sticky Bomb - Launch sticky explosive, detonate again to blow' 
        },
        'grappler': { 
            name: 'Grappler', 
            gltfPath: 'objects/cars/15-grapplersuv/',
            gltfFile: 'grappler.glb',
            scale: 2.0,
            rotationOffset: Math.PI + Math.PI / 2, 
            offset: { x: 0, y: -0.4, z: 0 },
            team: 5, 
            class: 'Heavy',
            color: 0x00ff88, 
            dimensions: { x: 2.5, y: 0.7, z: 5.5 }, 
            mass: 2000, 
            stats: { hp: 100, accel: 1.0, topSpeed: 1.0, jumpPower: 1.0, boostMult: 2.0, boostDur: 1.0, energyRegen: 1.0, nitroRegen: 1.0, ultCharge: 0, ultDmg: 1.0, bulletDmg: 1.0, bulletSpeed: 1.0, grip: 1.0 },
            wheels: [ { x: -1.9, y: -0.6, z: 2.8 }, { x: 1.9, y: -0.6, z: 2.8 }, { x: -1.9, y: -0.6, z: -2.8 }, { x: 1.9, y: -0.6, z: -2.8 } ],
            ult: 'Grapple - Latch onto barrel, hold & crush it' 
        },
        'f2': { 
            name: 'F2 Racer', 
            gltfPath: 'objects/cars/16-f2/',
            gltfFile: 'f2.glb',
            scale: 1.8,
            rotationOffset: Math.PI, 
            offset: { x: 0, y: -0.4, z: 0 },
            team: 6, 
            class: 'Light',
            color: 0x0000ff, 
            dimensions: { x: 2.5, y: 0.7, z: 5.5 }, 
            mass: 1100, 
            stats: { hp: 100, accel: 1.0, topSpeed: 1.0, jumpPower: 1.0, boostMult: 2.0, boostDur: 1.0, energyRegen: 1.0, nitroRegen: 1.0, ultCharge: 0, ultDmg: 1.0, bulletDmg: 1.0, bulletSpeed: 1.0, grip: 1.0 },
            wheels: [ { x: -1.9, y: -0.6, z: 2.8 }, { x: 1.9, y: -0.6, z: 2.8 }, { x: -1.9, y: -0.6, z: -2.8 }, { x: 1.9, y: -0.6, z: -2.8 } ],
            ult: 'Orbital Strike - 3 lightning beams from above' 
        },
        'rally': {
            name: 'Rally',
            gltfPath: 'objects/cars/17-rally/',
            gltfFile: 'rally.glb',
            scale: 1.7,
            rotationOffset: Math.PI,
            offset: { x: 0, y: -0.5, z: 0 },
            team: 6,
            class: 'Medium',
            color: 0xff6600,
            dimensions: { x: 2.5, y: 0.7, z: 5.5 },
            mass: 1500,
            stats: { hp: 100, accel: 1.0, topSpeed: 1.0, jumpPower: 1.0, boostMult: 2.0, boostDur: 1.0, energyRegen: 1.0, nitroRegen: 1.0, ultCharge: 0, ultDmg: 1.0, bulletDmg: 1.0, bulletSpeed: 1.0, grip: 1.0 },
            wheels: [ { x: -1.9, y: -0.6, z: 2.8 }, { x: 1.9, y: -0.6, z: 2.8 }, { x: -1.9, y: -0.6, z: -2.8 }, { x: 1.9, y: -0.6, z: -2.8 } ],
            ult: 'Default Projectile'
        },
        'livsuper': {
            name: 'Liv Super',
            gltfPath: 'objects/cars/18-livsuper/',
            gltfFile: 'dragsuper.glb',
            scale: 2.1,
            rotationOffset: Math.PI / 2,
            offset: { x: 0, y: -0.5, z: 0 },
            team: 6,
            class: 'Heavy',
            color: 0xdd0044,
            dimensions: { x: 2.5, y: 0.7, z: 5.5 },
            mass: 1400,
            stats: { hp: 100, accel: 1.0, topSpeed: 1.0, jumpPower: 1.0, boostMult: 2.0, boostDur: 1.0, energyRegen: 1.0, nitroRegen: 1.0, ultCharge: 0, ultDmg: 1.0, bulletDmg: 1.0, bulletSpeed: 1.0, grip: 1.0 },
            wheels: [ { x: -1.9, y: -0.6, z: 2.8 }, { x: 1.9, y: -0.6, z: 2.8 }, { x: -1.9, y: -0.6, z: -2.8 }, { x: 1.9, y: -0.6, z: -2.8 } ],
            ult: 'Default Projectile'
        },
        'bowcar': {
            name: 'Bow Car',
            team: 7,
            class: 'Light',
            gltfPath: 'objects/cars/19-bowcar/',
            gltfFile: 'bowgun.glb',
            scale: 1.8,
            rotationOffset: Math.PI,
            offset: { x: 0, y: -0.5, z: 0 },
            color: 0x884422,
            dimensions: { x: 2.5, y: 0.7, z: 5.5 },
            mass: 1600,
            stats: { hp: 100, accel: 1.0, topSpeed: 1.0, jumpPower: 1.0, boostMult: 2.0, boostDur: 1.0, energyRegen: 1.0, nitroRegen: 1.0, ultCharge: 0, ultDmg: 1.0, bulletDmg: 1.0, bulletSpeed: 1.0, grip: 1.0 },
            wheels: [ { x: -1.9, y: -0.6, z: 2.8 }, { x: 1.9, y: -0.6, z: 2.8 }, { x: -1.9, y: -0.6, z: -2.8 }, { x: 1.9, y: -0.6, z: -2.8 } ],
            ult: 'Arrow C4 - Fires an arrow with C4 that sticks, pushes, then explodes'
        },
        'muscle': {
            name: 'Muscle',
            team: 7,
            class: 'Medium',
            gltfPath: 'objects/cars/20-muscle/',
            gltfFile: 'carson_annihilator.glb',
            scale: 1.5,
            rotationOffset: Math.PI / 2,
            offset: { x: 0, y: -0.5, z: 0 },
            color: 0xcc2222,
            dimensions: { x: 2.5, y: 0.7, z: 5.5 },
            mass: 1800,
            stats: { hp: 100, accel: 1.0, topSpeed: 1.0, jumpPower: 1.0, boostMult: 2.0, boostDur: 1.0, energyRegen: 1.0, nitroRegen: 1.0, ultCharge: 0, ultDmg: 1.0, bulletDmg: 1.0, bulletSpeed: 1.0, grip: 1.0 },
            wheels: [ { x: -1.9, y: -0.6, z: 2.8 }, { x: 1.9, y: -0.6, z: 2.8 }, { x: -1.9, y: -0.6, z: -2.8 }, { x: 1.9, y: -0.6, z: -2.8 } ],
            ult: 'Wheelie Lunge - Pop a wheelie, hit a wall or car to launch sky-high like a hyperjump'
        },
        'willys': {
            name: "Willy's",
            team: 7,
            class: 'Heavy',
            gltfPath: 'objects/cars/21-lifted/',
            gltfFile: 'willys_mountain_buggy_2.glb',
            scale: 1.2,
            rotationOffset: Math.PI,
            offset: { x: 0, y: 0.3, z: 0 },
            color: 0x44aa44,
            dimensions: { x: 2.5, y: 0.7, z: 5.5 },
            mass: 1800,
            stats: { hp: 100, accel: 1.0, topSpeed: 1.0, jumpPower: 1.0, boostMult: 2.0, boostDur: 1.0, energyRegen: 1.0, nitroRegen: 1.0, ultCharge: 0, ultDmg: 1.0, bulletDmg: 1.0, bulletSpeed: 1.0, grip: 1.0 },
            wheels: [ { x: -1.9, y: -0.6, z: 2.8 }, { x: 1.9, y: -0.6, z: 2.8 }, { x: -1.9, y: -0.6, z: -2.8 }, { x: 1.9, y: -0.6, z: -2.8 } ],
            ult: 'Orbit Guard - Spawns 6 orbs that follow, detect, and pop enemies up'
        },
        'mini': { 
            name: 'Mini', 
            gltfPath: 'objects/cars/22-mini/',
            gltfFile: 'mini.glb',
            scale: 1.4,
            rotationOffset: Math.PI, 
            offset: { x: 0, y: -0.6, z: 0 },
            team: 8, 
            class: 'Light',
            color: 0xff0000, 
            dimensions: { x: 2.5, y: 0.7, z: 5.5 }, 
            mass: 1400, 
            stats: { hp: 100, accel: 1.0, topSpeed: 1.0, jumpPower: 1.0, boostMult: 2.0, boostDur: 1.0, energyRegen: 1.0, nitroRegen: 1.0, ultCharge: 0, ultDmg: 1.0, bulletDmg: 1.0, bulletSpeed: 1.0, grip: 1.0 },
            wheels: [ { x: -1.9, y: -0.6, z: 2.8 }, { x: 1.9, y: -0.6, z: 2.8 }, { x: -1.9, y: -0.6, z: -2.8 }, { x: 1.9, y: -0.6, z: -2.8 } ],
            ult: 'Homing Missiles - 3 tracking projectiles that curve to target' 
        },
        'sportssuper': { 
            name: 'Sports Super', 
            gltfPath: 'objects/cars/23-sport/',
            gltfFile: 'sportssuper.glb',
            scale: 1.9,
            rotationOffset: Math.PI, 
            offset: { x: 0, y: -0.5, z: 0 },
            team: 8, 
            class: 'Medium',
            color: 0xff0044, 
            dimensions: { x: 2.5, y: 0.7, z: 5.5 }, 
            mass: 1600, 
            stats: { hp: 100, accel: 1.0, topSpeed: 1.0, jumpPower: 1.0, boostMult: 2.0, boostDur: 1.0, energyRegen: 1.0, nitroRegen: 1.0, ultCharge: 0, ultDmg: 1.0, bulletDmg: 1.0, bulletSpeed: 1.0, grip: 1.0 },
            wheels: [ { x: -1.9, y: -0.6, z: 2.8 }, { x: 1.9, y: -0.6, z: 2.8 }, { x: -1.9, y: -0.6, z: -2.8 }, { x: 1.9, y: -0.6, z: -2.8 } ],
            ult: 'Flame Barrage - Rapid fire spread for 1.5s' 
        },
        'van': {
            name: 'Van',
            gltfPath: 'objects/cars/24-van/',
            gltfFile: 'van.glb',
            scale: 1.8,
            rotationOffset: Math.PI,
            offset: { x: 1, y: -0.4, z: -0.8 },
            team: 8,
            class: 'Heavy',
            color: 0x4488cc,
            dimensions: { x: 2.5, y: 0.7, z: 5.5 },
            mass: 1600,
            stats: { hp: 100, accel: 1.0, topSpeed: 1.0, jumpPower: 1.0, boostMult: 2.0, boostDur: 1.0, energyRegen: 1.0, nitroRegen: 1.0, ultCharge: 0, ultDmg: 1.0, bulletDmg: 1.0, bulletSpeed: 1.0, grip: 1.0 },
            wheels: [ { x: -1.9, y: -0.6, z: 2.8 }, { x: 1.9, y: -0.6, z: 2.8 }, { x: -1.9, y: -0.6, z: -2.8 }, { x: 1.9, y: -0.6, z: -2.8 } ],
            ult: 'Transform - Switch between van and sportbike forms'
        },
        'rougeai': {
            name: 'Rouge AI',
            gltfPath: 'objects/cars/25-rougeai/',
            gltfFile: 'sprintracer.glb',
            scale: 1.3,
            rotationOffset: Math.PI,
            offset: { x: 0, y: -0.5, z: 0 },
            team: 9,
            class: 'Light',
            color: 0x22cc22,
            dimensions: { x: 2.5, y: 0.7, z: 5.5 },
            mass: 1600,
            stats: { hp: 100, accel: 1.0, topSpeed: 1.0, jumpPower: 1.0, boostMult: 2.0, boostDur: 1.0, energyRegen: 1.0, nitroRegen: 1.0, ultCharge: 0, ultDmg: 1.0, bulletDmg: 1.0, bulletSpeed: 1.0, grip: 1.0 },
            wheels: [ { x: -1.9, y: -0.6, z: 2.8 }, { x: 1.9, y: -0.6, z: 2.8 }, { x: -1.9, y: -0.6, z: -2.8 }, { x: 1.9, y: -0.6, z: -2.8 } ],
            ult: 'Default Projectile'
        },
        'scorp': {
            name: 'Scorp',
            gltfPath: 'objects/cars/26-scorp/',
            gltfFile: 'bladecybercar.glb',
            scale: 1.8,
            rotationOffset: Math.PI,
            offset: { x: 0, y: -0.5, z: 0 },
            team: 9,
            class: 'Medium',
            color: 0x8866aa,
            dimensions: { x: 2.5, y: 0.7, z: 5.5 },
            mass: 1800,
            stats: { hp: 100, accel: 1.0, topSpeed: 1.0, jumpPower: 1.0, boostMult: 2.0, boostDur: 1.0, energyRegen: 1.0, nitroRegen: 1.0, ultCharge: 0, ultDmg: 1.0, bulletDmg: 1.0, bulletSpeed: 1.0, grip: 1.0 },
            wheels: [ { x: -1.9, y: -0.6, z: 2.8 }, { x: 1.9, y: -0.6, z: 2.8 }, { x: -1.9, y: -0.6, z: -2.8 }, { x: 1.9, y: -0.6, z: -2.8 } ],
            ult: 'Claw Grab - Throw a claw, grab a car, lift it, then fling it'
        },
        'nado': {
            name: 'Nado',
            gltfPath: 'objects/cars/27-nado/',
            gltfFile: 'nadotruck.glb',
            scale: 2.4,
            rotationOffset: Math.PI,
            offset: { x: 0, y: -0.5, z: 0 },
            team: 9,
            class: 'Heavy',
            color: 0x888800,
            dimensions: { x: 2.5, y: 0.7, z: 5.5 },
            mass: 1800,
            stats: { hp: 100, accel: 1.0, topSpeed: 1.0, jumpPower: 1.0, boostMult: 2.0, boostDur: 1.0, energyRegen: 1.0, nitroRegen: 1.0, ultCharge: 0, ultDmg: 1.0, bulletDmg: 1.0, bulletSpeed: 1.0, grip: 1.0 },
            wheels: [ { x: -1.9, y: -0.6, z: 2.8 }, { x: 1.9, y: -0.6, z: 2.8 }, { x: -1.9, y: -0.6, z: -2.8 }, { x: 1.9, y: -0.6, z: -2.8 } ],
            ult: 'Default Projectile'
        },
        '4door': { 
            name: '4 Door Sedan', 
            gltfPath: 'objects/cars/28-4door/',
            gltfFile: '4door.glb',
            scale: 1.8,
            rotationOffset: 0, 
            offset: { x: 0, y: -0.5, z: 0 },
            team: 10, 
            class: 'Light',
            color: 0xcccccc, 
            dimensions: { x: 2.5, y: 0.7, z: 5.5 }, 
            mass: 1600, 
            stats: { hp: 100, accel: 1.0, topSpeed: 1.0, jumpPower: 1.0, boostMult: 2.0, boostDur: 1.0, energyRegen: 1.0, nitroRegen: 1.0, ultCharge: 0, ultDmg: 1.0, bulletDmg: 1.0, bulletSpeed: 1.0, grip: 1.0 },
            wheels: [ { x: -1.9, y: -0.6, z: 2.8 }, { x: 1.9, y: -0.6, z: 2.8 }, { x: -1.9, y: -0.6, z: -2.8 }, { x: 1.9, y: -0.6, z: -2.8 } ],
            ult: 'Default Projectile' 
        },
        '61lowrider': { 
            name: '61 Lowrider', 
            objPath: 'objects/cars/29-lowrider/',
            objFile: 'lowrider.obj',
            mtlFile: 'lowrider.mtl',
            scale: 1.9,
            rotationOffset: Math.PI + Math.PI / 2, 
            offset: { x: 0, y: -0.3, z: 0 },
            team: 10, 
            class: 'Medium',
            color: 0xff00ff, 
            dimensions: { x: 2.5, y: 0.7, z: 5.5 }, 
            mass: 1600, 
            stats: { hp: 100, accel: 1.0, topSpeed: 1.0, jumpPower: 1.0, boostMult: 2.0, boostDur: 1.0, energyRegen: 1.0, nitroRegen: 1.0, ultCharge: 0, ultDmg: 1.0, bulletDmg: 1.0, bulletSpeed: 1.0, grip: 1.0 },
            wheels: [ { x: -1.9, y: -0.6, z: 2.8 }, { x: 1.9, y: -0.6, z: 2.8 }, { x: -1.9, y: -0.6, z: -2.8 }, { x: 1.9, y: -0.6, z: -2.8 } ],
            ult: 'Lowrider Slam - Massive jump, shockwave on landing' 
        },
        'tourbus': {
            name: 'Tour Bus',
            gltfPath: 'objects/cars/',
            gltfFile: 'schoolbus.glb',
            scale: 2.0,
            rotationOffset: Math.PI,
            offset: { x: 0, y: -0.5, z: 0 },
            team: 10,
            class: 'Heavy',
            color: 0xff88cc,
            dimensions: { x: 2.5, y: 0.7, z: 5.5 },
            mass: 1800,
            stats: { hp: 100, accel: 1.0, topSpeed: 1.0, jumpPower: 1.0, boostMult: 2.0, boostDur: 1.0, energyRegen: 1.0, nitroRegen: 1.0, ultCharge: 0, ultDmg: 1.0, bulletDmg: 1.0, bulletSpeed: 1.0, grip: 1.0 },
            wheels: [ { x: -1.9, y: -0.6, z: 2.8 }, { x: 1.9, y: -0.6, z: 2.8 }, { x: -1.9, y: -0.6, z: -2.8 }, { x: 1.9, y: -0.6, z: -2.8 } ],
            ult: 'Default Projectile'
        },
        'forklift': { 
            name: 'Forklift', 
            gltfPath: 'objects/cars/31-forklift/',
            gltfFile: 'Forklift.obj',
            scale: 1.0,
            rotationOffset: Math.PI * 1.5, 
            offset: { x: 0, y: -0.5, z: 0 },
            team: 11, 
            class: 'Light',
            color: 0xffaa00, 
            dimensions: { x: 2.5, y: 0.7, z: 5.5 }, 
            mass: 1800, 
            stats: { hp: 100, accel: 1.0, topSpeed: 1.0, jumpPower: 1.0, boostMult: 2.0, boostDur: 1.0, energyRegen: 1.0, nitroRegen: 1.0, ultCharge: 0, ultDmg: 1.0, bulletDmg: 1.0, bulletSpeed: 1.0, grip: 1.0 },
            wheels: [ { x: -1.9, y: -0.6, z: 2.8 }, { x: 1.9, y: -0.6, z: 2.8 }, { x: -1.9, y: -0.6, z: -2.8 }, { x: 1.9, y: -0.6, z: -2.8 } ],
            ult: 'Forklift Grab - Grab an enemy car, lift it, then slam it down and leap away' 
        },
        'flagtruck': {
            name: 'Flag Truck',
            gltfPath: 'objects/cars/32-flagtruck/',
            gltfFile: 'pick_up_truck_improvised_fighting_vehicle.glb',
            scale: 1.5,
            rotationOffset: Math.PI,
            offset: { x: 0, y: -0.5, z: 0 },
            team: 11,
            class: 'Medium',
            color: 0xcc4444,
            dimensions: { x: 2.5, y: 0.7, z: 5.5 },
            mass: 1800,
            stats: { hp: 100, accel: 1.0, topSpeed: 1.0, jumpPower: 1.0, boostMult: 2.0, boostDur: 1.0, energyRegen: 1.0, nitroRegen: 1.0, ultCharge: 0, ultDmg: 1.0, bulletDmg: 1.0, bulletSpeed: 1.0, grip: 1.0 },
            wheels: [ { x: -1.9, y: -0.6, z: 2.8 }, { x: 1.9, y: -0.6, z: 2.8 }, { x: -1.9, y: -0.6, z: -2.8 }, { x: 1.9, y: -0.6, z: -2.8 } ],
            ult: 'Default Projectile'
        },
        'mixer': { 
            name: 'Mixer', 
            gltfPath: 'objects/cars/',
            gltfFile: 'schoolbus.glb',
            scale: 2.0,
            rotationOffset: Math.PI, 
            offset: { x: 0, y: -0.5, z: 0 },
            team: 11, 
            class: 'Heavy',
            color: 0x44ff00, 
            dimensions: { x: 2.5, y: 0.7, z: 5.5 }, 
            mass: 1800, 
            stats: { hp: 100, accel: 1.0, topSpeed: 1.0, jumpPower: 1.0, boostMult: 2.0, boostDur: 1.0, energyRegen: 1.0, nitroRegen: 1.0, ultCharge: 0, ultDmg: 1.0, bulletDmg: 1.0, bulletSpeed: 1.0, grip: 1.0 },
            wheels: [ { x: -1.9, y: -0.6, z: 2.8 }, { x: 1.9, y: -0.6, z: 2.8 }, { x: -1.9, y: -0.6, z: -2.8 }, { x: 1.9, y: -0.6, z: -2.8 } ],
            ult: 'Toxic Trail - Dumps 5 toxic pools behind the car that last 10s' 
        },
        'miramar': {
            name: 'Miramar Z',
            objPath: 'objects/cars/34-demorally/',
            objFile: 'miramarZ.obj',
            mtlFile: 'miramarZ.mtl',
            scale: 1.6,
            rotationOffset: Math.PI,
            offset: { x: 0, y: -0.6, z: 0 },
            team: 12,
            class: 'Light',
            color: 0x00aaff,
            dimensions: { x: 2.5, y: 0.7, z: 5.5 },
            mass: 1600,
            stats: { hp: 100, accel: 1.0, topSpeed: 1.0, jumpPower: 1.0, boostMult: 2.0, boostDur: 1.0, energyRegen: 1.0, nitroRegen: 1.0, ultCharge: 0, ultDmg: 1.0, bulletDmg: 1.0, bulletSpeed: 1.0, grip: 1.0 },
            wheels: [ { x: -1.9, y: -0.6, z: 2.8 }, { x: 1.9, y: -0.6, z: 2.8 }, { x: -1.9, y: -0.6, z: -2.8 }, { x: 1.9, y: -0.6, z: -2.8 } ],
            ult: 'EMP Blast - Forward zap that shuts off a car and chains to another'
        },
        'democharger': { 
            name: 'Demo Charger', 
            gltfPath: 'objects/cars/35-democharger/',
            gltfFile: 'democharger.glb',
            scale: 1.7,
            rotationOffset: Math.PI, 
            offset: { x: 0, y: -0.3, z: -0.3 },
            team: 12, 
            class: 'Medium',
            color: 0xff8800, 
            dimensions: { x: 2.5, y: 0.7, z: 5.5 }, 
            mass: 1800, 
            stats: { hp: 100, accel: 1.0, topSpeed: 1.0, jumpPower: 1.0, boostMult: 2.0, boostDur: 1.0, energyRegen: 1.0, nitroRegen: 1.0, ultCharge: 0, ultDmg: 1.0, bulletDmg: 1.0, bulletSpeed: 1.0, grip: 1.0 },
            wheels: [ { x: -1.9, y: -0.6, z: 2.8 }, { x: 1.9, y: -0.6, z: 2.8 }, { x: -1.9, y: -0.6, z: -2.8 }, { x: 1.9, y: -0.6, z: -2.8 } ],
            ult: 'Default Projectile' 
        },
        'semi': { 
            name: 'Semi Truck', 
            gltfPath: 'objects/cars/36-demosemi/',
            gltfFile: 'semi.glb',
            scale: 2.6,
            rotationOffset: Math.PI, 
            offset: { x: 0, y: -0.3, z: 0 },
            team: 12, 
            class: 'Heavy',
            color: 0x555555, 
            dimensions: { x: 2.5, y: 0.7, z: 5.5 }, 
            mass: 1900, 
            stats: { hp: 100, accel: 1.0, topSpeed: 1.0, jumpPower: 1.0, boostMult: 2.0, boostDur: 1.0, energyRegen: 1.0, nitroRegen: 1.0, ultCharge: 0, ultDmg: 1.0, bulletDmg: 1.0, bulletSpeed: 1.0, grip: 1.0 },
            wheels: [ { x: -1.9, y: -0.6, z: 2.8 }, { x: 1.9, y: -0.6, z: 2.8 }, { x: -1.9, y: -0.6, z: -2.8 }, { x: 1.9, y: -0.6, z: -2.8 } ],
            ult: 'Trailer Hitch - Trailer follows behind, hits consume ult ammo, trailer destroyed at 0 ammo' 
        },
        'voidbike': {
            name: 'Void Bike',
            gltfPath: 'objects/cars/37-voidbike/',
            gltfFile: 'hoverbike.glb',
            scale: 1.2,
            rotationOffset: Math.PI / 2,
            offset: { x: 0, y: -0.5, z: 0 },
            team: 13,
            class: 'Light',
            color: 0x660066,
            dimensions: { x: 2.5, y: 0.7, z: 5.5 },
            mass: 1200,
            stats: { hp: 100, accel: 1.0, topSpeed: 1.0, jumpPower: 1.0, boostMult: 2.0, boostDur: 1.0, energyRegen: 1.0, nitroRegen: 1.0, ultCharge: 0, ultDmg: 1.0, bulletDmg: 1.0, bulletSpeed: 1.0, grip: 1.0 },
            wheels: [ { x: -1.9, y: -0.6, z: 2.8 }, { x: 1.9, y: -0.6, z: 2.8 }, { x: -1.9, y: -0.6, z: -2.8 }, { x: 1.9, y: -0.6, z: -2.8 } ],
            ult: 'Default Projectile'
        },
        'voidcar': {
            name: 'Void Car',
            gltfPath: 'objects/cars/38-voidcar/',
            gltfFile: 'futuristic_car.glb',
            scale: 2.0,
            rotationOffset: Math.PI / 2,
            offset: { x: -0.5, y: -0.5, z: 0 },
            team: 13,
            class: 'Medium',
            color: 0x4400aa,
            dimensions: { x: 2.5, y: 0.7, z: 5.5 },
            mass: 1600,
            stats: { hp: 100, accel: 1.0, topSpeed: 1.0, jumpPower: 1.0, boostMult: 2.0, boostDur: 1.0, energyRegen: 1.0, nitroRegen: 1.0, ultCharge: 0, ultDmg: 1.0, bulletDmg: 1.0, bulletSpeed: 1.0, grip: 1.0 },
            wheels: [ { x: -1.9, y: -0.6, z: 2.8 }, { x: 1.9, y: -0.6, z: 2.8 }, { x: -1.9, y: -0.6, z: -2.8 }, { x: 1.9, y: -0.6, z: -2.8 } ],
            ult: 'Default Projectile'
        },
        'tractor': {
            name: 'Tractor',
            objPath: 'objects/cars/39-voidtractor/',
            objFile: 'Tractor.obj',
            scale: 1.7,
            rotationOffset: Math.PI,
            offset: { x: 0, y: 0, z: -1.5 },
            team: 13,
            class: 'Heavy',
            color: 0x886600,
            dimensions: { x: 2.8, y: 1.0, z: 5.5 },
            mass: 2000,
            stats: { hp: 100, accel: 1.0, topSpeed: 1.0, jumpPower: 1.0, boostMult: 2.0, boostDur: 1.0, energyRegen: 1.0, nitroRegen: 1.0, ultCharge: 0, ultDmg: 1.0, bulletDmg: 1.0, bulletSpeed: 1.0, grip: 1.0 },
            wheels: [ { x: -1.9, y: -0.6, z: 2.8 }, { x: 1.9, y: -0.6, z: 2.8 }, { x: -1.9, y: -0.6, z: -2.8 }, { x: 1.9, y: -0.6, z: -2.8 } ],
            ult: 'Grind & Toss - Grab a car, grind it with damage, then toss it sky-high'
        },
        'oldrace': {
            name: 'Old Race',
            objPath: 'objects/cars/40-oldrace/',
            objFile: 'raceoldconceptcar.obj',
            mtlFile: 'raceoldconceptcar.mtl',
            scale: 1.6,
            rotationOffset: Math.PI,
            offset: { x: 0, y: -0.6, z: 0 },
            team: 14,
            class: 'Light',
            color: 0xcc4400,
            dimensions: { x: 2.5, y: 0.7, z: 5.5 },
            mass: 1500,
            stats: { hp: 100, accel: 1.0, topSpeed: 1.0, jumpPower: 1.0, boostMult: 2.0, boostDur: 1.0, energyRegen: 1.0, nitroRegen: 1.0, ultCharge: 0, ultDmg: 1.0, bulletDmg: 1.0, bulletSpeed: 1.0, grip: 1.0 },
            wheels: [ { x: -1.9, y: -0.6, z: 2.8 }, { x: 1.9, y: -0.6, z: 2.8 }, { x: -1.9, y: -0.6, z: -2.8 }, { x: 1.9, y: -0.6, z: -2.8 } ],
            ult: 'Default Projectile'
        },
        'spycar': {
            name: 'Spy Car',
            gltfPath: 'objects/cars/41-spycar/',
            gltfFile: 'spycar.glb',
            scale: 1.8,
            rotationOffset: Math.PI,
            offset: { x: 0, y: -0.6, z: 0 },
            team: 14,
            class: 'Medium',
            color: 0x222222,
            dimensions: { x: 2.5, y: 0.7, z: 5.5 },
            mass: 1600,
            stats: { hp: 100, accel: 1.0, topSpeed: 1.0, jumpPower: 1.0, boostMult: 2.0, boostDur: 1.0, energyRegen: 1.0, nitroRegen: 1.0, ultCharge: 0, ultDmg: 1.0, bulletDmg: 1.0, bulletSpeed: 1.0, grip: 1.0 },
            wheels: [ { x: -1.9, y: -0.6, z: 2.8 }, { x: 1.9, y: -0.6, z: 2.8 }, { x: -1.9, y: -0.6, z: -2.8 }, { x: 1.9, y: -0.6, z: -2.8 } ],
            ult: 'Missile Swarm - Fires 10 homing missiles'
        },
        'redrum': { 
            name: 'Redrum', 
            gltfPath: 'objects/cars/42-redrum/',
            gltfFile: 'redrum.glb',
            scale: 1.7,
            rotationOffset: Math.PI / 2,
            offset: { x: 0, y: -0.3, z: 0 },
            team: 14, 
            class: 'Heavy',
            color: 0xff0000, 
            dimensions: { x: 2.5, y: 0.7, z: 5.5 }, 
            mass: 1800, 
            stats: { hp: 100, accel: 1.0, topSpeed: 1.0, jumpPower: 1.0, boostMult: 2.0, boostDur: 1.0, energyRegen: 1.0, nitroRegen: 1.0, ultCharge: 0, ultDmg: 1.0, bulletDmg: 1.0, bulletSpeed: 1.0, grip: 1.0 },
            wheels: [ { x: -1.9, y: -0.6, z: 2.8 }, { x: 1.9, y: -0.6, z: 2.8 }, { x: -1.9, y: -0.6, z: -2.8 }, { x: 1.9, y: -0.6, z: -2.8 } ],
            ult: 'Barrel Launcher - Fires explosive/toxic/cryo barrels' 
        },
        'planecar': {
            name: 'Plane Car',
            fbxPath: 'objects/cars/43-thefoldplanecar/',
            fbxFile: 'plane car.fbx',
            scale: 1.9,
            rotationOffset: Math.PI,
            offset: { x: 0, y: -0.5, z: 0 },
            team: 15,
            class: 'Light',
            color: 0x88aacc,
            dimensions: { x: 2.5, y: 0.7, z: 5.5 },
            mass: 1600,
            stats: { hp: 100, accel: 1.0, topSpeed: 1.0, jumpPower: 1.0, boostMult: 2.0, boostDur: 1.0, energyRegen: 1.0, nitroRegen: 1.0, ultCharge: 0, ultDmg: 1.0, bulletDmg: 1.0, bulletSpeed: 1.0, grip: 1.0 },
            wheels: [ { x: -1.9, y: -0.6, z: 2.8 }, { x: 1.9, y: -0.6, z: 2.8 }, { x: -1.9, y: -0.6, z: -2.8 }, { x: 1.9, y: -0.6, z: -2.8 } ],
            ult: 'Aerial Mine Lay - Fly up, glide, drop rolling spike balls that stop after 3s'
        },
        'humher': { 
            name: 'Humher', 
            objPath: 'objects/cars/44-thefoldhumher/',
            objFile: 'humer.obj',
            mtlFile: 'humer.mtl',
            scale: 1.5,
            rotationOffset: Math.PI, 
            offset: { x: 0, y: -0.5, z: 0 },
            team: 15, 
            class: 'Medium',
            color: 0x445522, 
            dimensions: { x: 2.5, y: 0.7, z: 5.5 }, 
            mass: 1800, 
            stats: { hp: 100, accel: 1.0, topSpeed: 1.0, jumpPower: 1.0, boostMult: 2.0, boostDur: 1.0, energyRegen: 1.0, nitroRegen: 1.0, ultCharge: 0, ultDmg: 1.0, bulletDmg: 1.0, bulletSpeed: 1.0, grip: 1.0 },
            wheels: [ { x: -1.9, y: -0.6, z: 2.8 }, { x: 1.9, y: -0.6, z: 2.8 }, { x: -1.9, y: -0.6, z: -2.8 }, { x: 1.9, y: -0.6, z: -2.8 } ],
            ult: 'Auto-Turret - Rapid fire at nearest target for 2s' 
        },
        'schoolbus': { 
            name: 'School Bus', 
            gltfPath: 'objects/cars/45-thefoldstuntbus/',
            gltfFile: 'schoolbus.glb',
            scale: 2.0,
            rotationOffset: Math.PI, 
            offset: { x: 0, y: -0.5, z: 0 },
            team: 15, 
            class: 'Heavy',
            color: 0xffcc00, 
            dimensions: { x: 2.5, y: 0.7, z: 5.5 }, 
            mass: 1800, 
            stats: { hp: 100, accel: 1.0, topSpeed: 1.0, jumpPower: 1.0, boostMult: 2.0, boostDur: 1.0, energyRegen: 1.0, nitroRegen: 1.0, ultCharge: 0, ultDmg: 1.0, bulletDmg: 1.0, bulletSpeed: 1.0, grip: 1.0 },
            wheels: [ { x: -1.9, y: -0.6, z: 2.8 }, { x: 1.9, y: -0.6, z: 2.8 }, { x: -1.9, y: -0.6, z: -2.8 }, { x: 1.9, y: -0.6, z: -2.8 } ],
            ult: 'Laser Zap - Lightning-fast beam hits target instantly' 
        },
        'yellowelstang': { 
            name: 'Yellow Elstang', 
            gltfPath: 'objects/cars/46-yellowelstang/',
            gltfFile: 'mazda_miata_mx-5_offroad.glb',
            scale: 1.6,
            rotationOffset: Math.PI, 
            offset: { x: 0, y: -0.4, z: 0 },
            team: 16, 
            class: 'Light',
            color: 0xffdd00, 
            dimensions: { x: 2.5, y: 0.7, z: 5.5 }, 
            mass: 1800, 
            stats: { hp: 100, accel: 1.0, topSpeed: 1.0, jumpPower: 1.0, boostMult: 2.0, boostDur: 1.0, energyRegen: 1.0, nitroRegen: 1.0, ultCharge: 0, ultDmg: 1.0, bulletDmg: 1.0, bulletSpeed: 1.0, grip: 1.0 },
            wheels: [ { x: -1.9, y: -0.6, z: 2.8 }, { x: 1.9, y: -0.6, z: 2.8 }, { x: -1.9, y: -0.6, z: -2.8 }, { x: 1.9, y: -0.6, z: -2.8 } ],
            ult: 'Piercing Shot - High-damage sniper round, 3x speed' 
        },
        'rocketcar': { 
            name: 'Rocket Car', 
            gltfPath: 'objects/cars/47-rocketcar/',
            gltfFile: 'rocketcar.glb',
            scale: 1.8,
            rotationOffset: Math.PI, 
            offset: { x: 0, y: -0.4, z: 0 },
            team: 16, 
            class: 'Medium',
            color: 0xcccccc, 
            dimensions: { x: 2.5, y: 0.7, z: 5.5 }, 
            mass: 1300, 
            stats: { hp: 100, accel: 1.0, topSpeed: 1.0, jumpPower: 1.0, boostMult: 2.0, boostDur: 1.0, energyRegen: 1.0, nitroRegen: 1.0, ultCharge: 0, ultDmg: 1.0, bulletDmg: 1.0, bulletSpeed: 1.0, grip: 1.0 },
            wheels: [ { x: -1.9, y: -0.6, z: 2.8 }, { x: 1.9, y: -0.6, z: 2.8 }, { x: -1.9, y: -0.6, z: -2.8 }, { x: 1.9, y: -0.6, z: -2.8 } ],
            ult: 'Rocket Boost - Massive forward thrust, damages anything hit' 
        },
        'wolfstreet': {
            name: 'Wolf Street',
            gltfPath: 'objects/cars/48-wolfstreet/',
            gltfFile: 'source.glb',
            scale: 1.7,
            rotationOffset: Math.PI,
            offset: { x: 0, y: -0.5, z: 0 },
            team: 16,
            class: 'Heavy',
            color: 0x888888,
            dimensions: { x: 2.5, y: 0.7, z: 5.5 },
            mass: 1600,
            stats: { hp: 100, accel: 1.0, topSpeed: 1.0, jumpPower: 1.0, boostMult: 2.0, boostDur: 1.0, energyRegen: 1.0, nitroRegen: 1.0, ultCharge: 0, ultDmg: 1.0, bulletDmg: 1.0, bulletSpeed: 1.0, grip: 1.0 },
            wheels: [ { x: -1.9, y: -0.6, z: 2.8 }, { x: 1.9, y: -0.6, z: 2.8 }, { x: -1.9, y: -0.6, z: -2.8 }, { x: 1.9, y: -0.6, z: -2.8 } ],
            ult: 'Fire Tornado - Spins the car while fire storm lifts and flings enemies'
        },
        'bumsboss': {
            name: 'Bums Boss',
            gltfPath: 'objects/cars/',
            gltfFile: 'schoolbus.glb',
            scale: 2.0,
            rotationOffset: Math.PI,
            offset: { x: 0, y: -0.5, z: 0 },
            team: 1,
            class: 'boss',
            color: 0xcc44aa,
            dimensions: { x: 3.0, y: 1.2, z: 6.0 },
            mass: 2500,
            stats: { hp: 100, accel: 1.0, topSpeed: 1.0, jumpPower: 1.0, boostMult: 2.0, boostDur: 1.0, energyRegen: 1.0, nitroRegen: 1.0, ultCharge: 0, ultDmg: 1.0, bulletDmg: 1.0, bulletSpeed: 1.0, grip: 1.0 },
            wheels: [ { x: -1.9, y: -0.6, z: 2.8 }, { x: 1.9, y: -0.6, z: 2.8 }, { x: -1.9, y: -0.6, z: -2.8 }, { x: 1.9, y: -0.6, z: -2.8 } ],
            ult: 'Default Projectile'
        },
        'z2-ufo': { 
            name: 'UFO', 
            objPath: 'objects/cars/z2-space/',
            objFile: 'UFO2.obj',
            mtlFile: 'UFO2.mtl',
            scale: 2.0, 
            rotationOffset: 0,
            alwaysHover: true,
            team: 2, 
            class: 'boss',
            color: 0x00ff00, 
            dimensions: { x: 3.0, y: 3.0, z: 3.0 }, 
            mass: 2400, 
            stats: { hp: 100, accel: 1.0, topSpeed: 1.0, jumpPower: 1.0, boostMult: 2.0, boostDur: 1.0, energyRegen: 1.0, nitroRegen: 1.0, ultCharge: 0, ultDmg: 1.0, bulletDmg: 1.0, bulletSpeed: 1.0, grip: 1.0 },
            wheels: [],
            ult: 'Tractor Beam - Lift barrels, slam them down for damage' 
        },
        'ratsboss': {
            name: 'Rats Boss',
            gltfPath: 'objects/cars/',
            gltfFile: 'schoolbus.glb',
            scale: 2.0,
            rotationOffset: Math.PI,
            offset: { x: 0, y: -0.5, z: 0 },
            team: 3,
            class: 'boss',
            color: 0x884400,
            dimensions: { x: 3.0, y: 1.2, z: 6.0 },
            mass: 2500,
            stats: { hp: 100, accel: 1.0, topSpeed: 1.0, jumpPower: 1.0, boostMult: 2.0, boostDur: 1.0, energyRegen: 1.0, nitroRegen: 1.0, ultCharge: 0, ultDmg: 1.0, bulletDmg: 1.0, bulletSpeed: 1.0, grip: 1.0 },
            wheels: [ { x: -1.9, y: -0.6, z: 2.8 }, { x: 1.9, y: -0.6, z: 2.8 }, { x: -1.9, y: -0.6, z: -2.8 }, { x: 1.9, y: -0.6, z: -2.8 } ],
            ult: 'Default Projectile'
        },
        'hackerboss': {
            name: 'Hacker Boss',
            gltfPath: 'objects/cars/',
            gltfFile: 'schoolbus.glb',
            scale: 2.0,
            rotationOffset: Math.PI,
            offset: { x: 0, y: -0.5, z: 0 },
            team: 4,
            class: 'boss',
            color: 0x00cc44,
            dimensions: { x: 3.0, y: 1.2, z: 6.0 },
            mass: 2500,
            stats: { hp: 100, accel: 1.0, topSpeed: 1.0, jumpPower: 1.0, boostMult: 2.0, boostDur: 1.0, energyRegen: 1.0, nitroRegen: 1.0, ultCharge: 0, ultDmg: 1.0, bulletDmg: 1.0, bulletSpeed: 1.0, grip: 1.0 },
            wheels: [ { x: -1.9, y: -0.6, z: 2.8 }, { x: 1.9, y: -0.6, z: 2.8 }, { x: -1.9, y: -0.6, z: -2.8 }, { x: 1.9, y: -0.6, z: -2.8 } ],
            ult: 'Default Projectile'
        },
        'policeboss': {
            name: 'Police Boss',
            gltfPath: 'objects/cars/',
            gltfFile: 'schoolbus.glb',
            scale: 2.0,
            rotationOffset: Math.PI,
            offset: { x: 0, y: -0.5, z: 0 },
            team: 5,
            class: 'boss',
            color: 0x2222aa,
            dimensions: { x: 3.0, y: 1.2, z: 6.0 },
            mass: 2500,
            stats: { hp: 100, accel: 1.0, topSpeed: 1.0, jumpPower: 1.0, boostMult: 2.0, boostDur: 1.0, energyRegen: 1.0, nitroRegen: 1.0, ultCharge: 0, ultDmg: 1.0, bulletDmg: 1.0, bulletSpeed: 1.0, grip: 1.0 },
            wheels: [ { x: -1.9, y: -0.6, z: 2.8 }, { x: 1.9, y: -0.6, z: 2.8 }, { x: -1.9, y: -0.6, z: -2.8 }, { x: 1.9, y: -0.6, z: -2.8 } ],
            ult: 'Default Projectile'
        },
        'jammonsterboss': {
            name: 'Jam Monster Boss',
            gltfPath: 'objects/cars/',
            gltfFile: 'schoolbus.glb',
            scale: 2.0,
            rotationOffset: Math.PI,
            offset: { x: 0, y: -0.5, z: 0 },
            team: 6,
            class: 'boss',
            color: 0xaa44ff,
            dimensions: { x: 3.0, y: 1.2, z: 6.0 },
            mass: 2500,
            stats: { hp: 100, accel: 1.0, topSpeed: 1.0, jumpPower: 1.0, boostMult: 2.0, boostDur: 1.0, energyRegen: 1.0, nitroRegen: 1.0, ultCharge: 0, ultDmg: 1.0, bulletDmg: 1.0, bulletSpeed: 1.0, grip: 1.0 },
            wheels: [ { x: -1.9, y: -0.6, z: 2.8 }, { x: 1.9, y: -0.6, z: 2.8 }, { x: -1.9, y: -0.6, z: -2.8 }, { x: 1.9, y: -0.6, z: -2.8 } ],
            ult: 'Default Projectile'
        },
        'junkboss': {
            name: 'Junk Boss',
            gltfPath: 'objects/cars/',
            gltfFile: 'schoolbus.glb',
            scale: 2.0,
            rotationOffset: Math.PI,
            offset: { x: 0, y: -0.5, z: 0 },
            team: 7,
            class: 'boss',
            color: 0x886622,
            dimensions: { x: 3.0, y: 1.2, z: 6.0 },
            mass: 2500,
            stats: { hp: 100, accel: 1.0, topSpeed: 1.0, jumpPower: 1.0, boostMult: 2.0, boostDur: 1.0, energyRegen: 1.0, nitroRegen: 1.0, ultCharge: 0, ultDmg: 1.0, bulletDmg: 1.0, bulletSpeed: 1.0, grip: 1.0 },
            wheels: [ { x: -1.9, y: -0.6, z: 2.8 }, { x: 1.9, y: -0.6, z: 2.8 }, { x: -1.9, y: -0.6, z: -2.8 }, { x: 1.9, y: -0.6, z: -2.8 } ],
            ult: 'Default Projectile'
        },
        'cuteboss': {
            name: 'Cute Boss',
            gltfPath: 'objects/cars/',
            gltfFile: 'schoolbus.glb',
            scale: 2.0,
            rotationOffset: Math.PI,
            offset: { x: 0, y: -0.5, z: 0 },
            team: 8,
            class: 'boss',
            color: 0xff88cc,
            dimensions: { x: 3.0, y: 1.2, z: 6.0 },
            mass: 2500,
            stats: { hp: 100, accel: 1.0, topSpeed: 1.0, jumpPower: 1.0, boostMult: 2.0, boostDur: 1.0, energyRegen: 1.0, nitroRegen: 1.0, ultCharge: 0, ultDmg: 1.0, bulletDmg: 1.0, bulletSpeed: 1.0, grip: 1.0 },
            wheels: [ { x: -1.9, y: -0.6, z: 2.8 }, { x: 1.9, y: -0.6, z: 2.8 }, { x: -1.9, y: -0.6, z: -2.8 }, { x: 1.9, y: -0.6, z: -2.8 } ],
            ult: 'Default Projectile'
        },
        'finaltank': { 
            name: 'Final Tank', 
            gltfPath: 'objects/cars/z9-finaltank/',
            gltfFile: 'Final Tank.glb',
            scale: 2.2,
            rotationOffset: Math.PI + Math.PI / 2, 
            offset: { x: 0, y: -0.3, z: 0 },
            team: 9, 
            class: 'boss',
            color: 0x444400, 
            dimensions: { x: 2.5, y: 0.7, z: 5.5 }, 
            mass: 2200, 
            stats: { hp: 100, accel: 1.0, topSpeed: 1.0, jumpPower: 1.0, boostMult: 2.0, boostDur: 1.0, energyRegen: 1.0, nitroRegen: 1.0, ultCharge: 0, ultDmg: 1.0, bulletDmg: 1.0, bulletSpeed: 1.0, grip: 1.0 },
            wheels: [ { x: -1.9, y: -0.6, z: 2.8 }, { x: 1.9, y: -0.6, z: 2.8 }, { x: -1.9, y: -0.6, z: -2.8 }, { x: 1.9, y: -0.6, z: -2.8 } ],
            ult: 'Default Projectile' 
        },
        'bigboss': {
            name: 'Big Boss',
            gltfPath: 'objects/cars/',
            gltfFile: 'schoolbus.glb',
            scale: 2.0,
            rotationOffset: Math.PI,
            offset: { x: 0, y: -0.5, z: 0 },
            team: 10,
            class: 'boss',
            color: 0x88aa00,
            dimensions: { x: 3.0, y: 1.2, z: 6.0 },
            mass: 2500,
            stats: { hp: 100, accel: 1.0, topSpeed: 1.0, jumpPower: 1.0, boostMult: 2.0, boostDur: 1.0, energyRegen: 1.0, nitroRegen: 1.0, ultCharge: 0, ultDmg: 1.0, bulletDmg: 1.0, bulletSpeed: 1.0, grip: 1.0 },
            wheels: [ { x: -1.9, y: -0.6, z: 2.8 }, { x: 1.9, y: -0.6, z: 2.8 }, { x: -1.9, y: -0.6, z: -2.8 }, { x: 1.9, y: -0.6, z: -2.8 } ],
            ult: 'Default Projectile'
        },
        'cranetruck': {
            name: 'Crane Truck',
            gltfPath: 'objects/cars/',
            gltfFile: 'schoolbus.glb',
            scale: 2.0,
            rotationOffset: Math.PI,
            offset: { x: 0, y: -0.5, z: 0 },
            team: 11,
            class: 'boss',
            color: 0xffaa00,
            dimensions: { x: 3.0, y: 1.2, z: 6.0 },
            mass: 2500,
            stats: { hp: 100, accel: 1.0, topSpeed: 1.0, jumpPower: 1.0, boostMult: 2.0, boostDur: 1.0, energyRegen: 1.0, nitroRegen: 1.0, ultCharge: 0, ultDmg: 1.0, bulletDmg: 1.0, bulletSpeed: 1.0, grip: 1.0 },
            wheels: [ { x: -1.9, y: -0.6, z: 2.8 }, { x: 1.9, y: -0.6, z: 2.8 }, { x: -1.9, y: -0.6, z: -2.8 }, { x: 1.9, y: -0.6, z: -2.8 } ],
            ult: 'Default Projectile'
        },
        'demoboss': {
            name: 'Demo Boss Dumptruck',
            gltfPath: 'objects/cars/',
            gltfFile: 'schoolbus.glb',
            scale: 2.0,
            rotationOffset: Math.PI,
            offset: { x: 0, y: -0.5, z: 0 },
            team: 12,
            class: 'boss',
            color: 0xff4400,
            dimensions: { x: 3.0, y: 1.2, z: 6.0 },
            mass: 2500,
            stats: { hp: 100, accel: 1.0, topSpeed: 1.0, jumpPower: 1.0, boostMult: 2.0, boostDur: 1.0, energyRegen: 1.0, nitroRegen: 1.0, ultCharge: 0, ultDmg: 1.0, bulletDmg: 1.0, bulletSpeed: 1.0, grip: 1.0 },
            wheels: [ { x: -1.9, y: -0.6, z: 2.8 }, { x: 1.9, y: -0.6, z: 2.8 }, { x: -1.9, y: -0.6, z: -2.8 }, { x: 1.9, y: -0.6, z: -2.8 } ],
            ult: 'Default Projectile'
        },
        'voidboss': {
            name: 'Void Boss',
            gltfPath: 'objects/cars/',
            gltfFile: 'schoolbus.glb',
            scale: 2.0,
            rotationOffset: Math.PI,
            offset: { x: 0, y: -0.5, z: 0 },
            team: 13,
            class: 'boss',
            color: 0x440066,
            dimensions: { x: 3.0, y: 1.2, z: 6.0 },
            mass: 2500,
            stats: { hp: 100, accel: 1.0, topSpeed: 1.0, jumpPower: 1.0, boostMult: 2.0, boostDur: 1.0, energyRegen: 1.0, nitroRegen: 1.0, ultCharge: 0, ultDmg: 1.0, bulletDmg: 1.0, bulletSpeed: 1.0, grip: 1.0 },
            wheels: [ { x: -1.9, y: -0.6, z: 2.8 }, { x: 1.9, y: -0.6, z: 2.8 }, { x: -1.9, y: -0.6, z: -2.8 }, { x: 1.9, y: -0.6, z: -2.8 } ],
            ult: 'Default Projectile'
        },
        'radioboss': {
            name: 'Radio Boss',
            gltfPath: 'objects/cars/',
            gltfFile: 'schoolbus.glb',
            scale: 2.0,
            rotationOffset: Math.PI,
            offset: { x: 0, y: -0.5, z: 0 },
            team: 14,
            class: 'boss',
            color: 0x44aacc,
            dimensions: { x: 3.0, y: 1.2, z: 6.0 },
            mass: 2500,
            stats: { hp: 100, accel: 1.0, topSpeed: 1.0, jumpPower: 1.0, boostMult: 2.0, boostDur: 1.0, energyRegen: 1.0, nitroRegen: 1.0, ultCharge: 0, ultDmg: 1.0, bulletDmg: 1.0, bulletSpeed: 1.0, grip: 1.0 },
            wheels: [ { x: -1.9, y: -0.6, z: 2.8 }, { x: 1.9, y: -0.6, z: 2.8 }, { x: -1.9, y: -0.6, z: -2.8 }, { x: 1.9, y: -0.6, z: -2.8 } ],
            ult: 'Default Projectile'
        },
        'armyboss': {
            name: 'Army Boss',
            gltfPath: 'objects/cars/',
            gltfFile: 'schoolbus.glb',
            scale: 2.0,
            rotationOffset: Math.PI,
            offset: { x: 0, y: -0.5, z: 0 },
            team: 15,
            class: 'boss',
            color: 0x445522,
            dimensions: { x: 3.0, y: 1.2, z: 6.0 },
            mass: 2500,
            stats: { hp: 100, accel: 1.0, topSpeed: 1.0, jumpPower: 1.0, boostMult: 2.0, boostDur: 1.0, energyRegen: 1.0, nitroRegen: 1.0, ultCharge: 0, ultDmg: 1.0, bulletDmg: 1.0, bulletSpeed: 1.0, grip: 1.0 },
            wheels: [ { x: -1.9, y: -0.6, z: 2.8 }, { x: 1.9, y: -0.6, z: 2.8 }, { x: -1.9, y: -0.6, z: -2.8 }, { x: 1.9, y: -0.6, z: -2.8 } ],
            ult: 'Default Projectile'
        },
        'prostreetboss': {
            name: 'Pro Street Boss',
            gltfPath: 'objects/cars/',
            gltfFile: 'schoolbus.glb',
            scale: 2.0,
            rotationOffset: Math.PI,
            offset: { x: 0, y: -0.5, z: 0 },
            team: 16,
            class: 'boss',
            color: 0xcc2200,
            dimensions: { x: 3.0, y: 1.2, z: 6.0 },
            mass: 2500,
            stats: { hp: 100, accel: 1.0, topSpeed: 1.0, jumpPower: 1.0, boostMult: 2.0, boostDur: 1.0, energyRegen: 1.0, nitroRegen: 1.0, ultCharge: 0, ultDmg: 1.0, bulletDmg: 1.0, bulletSpeed: 1.0, grip: 1.0 },
            wheels: [ { x: -1.9, y: -0.6, z: 2.8 }, { x: 1.9, y: -0.6, z: 2.8 }, { x: -1.9, y: -0.6, z: -2.8 }, { x: 1.9, y: -0.6, z: -2.8 } ],
            ult: 'Default Projectile'
        },
        '35-impala': { 
            name: 'Impala', 
            gltfPath: 'objects/cars/devteam/',
            gltfFile: 'scene.gltf',
            scale: 2.0,
            rotationOffset: Math.PI, 
            offset: { x: 0, y: -0.3, z: 0 },
            team: 0, 
            class: 'dev',
            color: 0x4488ff, 
            dimensions: { x: 2.5, y: 0.7, z: 5.5 }, 
            mass: 1400, 
            stats: { hp: 100, accel: 1.0, topSpeed: 1.0, jumpPower: 1.0, boostMult: 2.0, boostDur: 1.0, energyRegen: 1.0, nitroRegen: 1.0, ultCharge: 0, ultDmg: 1.0, bulletDmg: 1.0, bulletSpeed: 1.0, grip: 1.0 },
            wheels: [ { x: -1.9, y: -0.6, z: 2.8 }, { x: 1.9, y: -0.6, z: 2.8 }, { x: -1.9, y: -0.6, z: -2.8 }, { x: 1.9, y: -0.6, z: -2.8 } ],
            ult: 'Shockwave - Emits a ring that pushes & damages nearby barrels' 
        },
    }
};
